AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://awsbrooks/84a88da0f2040df82decc0885159f412
      Environment:
        Variables:
          S3_BUCKET: awsbrooks
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
